workflows:
  default-workflow:
    name: Default Workflow for ditonton
    instance_type: mac_mini_m2
    max_build_duration: 60

    inputs:
      name:
        description: Input description
        default: Codemagic

    environment:
      groups:
        - firebase_credentials
      flutter: stable
      xcode: latest
      android_signing:
        - keystore_ditonton

    cache:
      cache_paths:
        - ~/.pub-cache

    triggering:
      events:
        - push

      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get dependencies and run build_runner
        script: |
          flutter pub get
          echo "Running build_runner..."
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run tests with coverage
        script: |
          chmod +x ./test.sh
          ./test.sh
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e # exit on first failed command

          PROJECT_ROOT=$CM_BUILD_DIR   # ADD YOUR PROJECT FOLDER PATH HERE

          echo "Decoding Firebase credentials..."
          echo $ANDROID_FIREBASE_SECRET | base64 --decode > $PROJECT_ROOT/android/app/google-services.json
          echo $IOS_FIREBASE_SECRET | base64 --decode > $PROJECT_ROOT/ios/Runner/GoogleService-Info.plist
          echo "Firebase configuration successfully loaded!"
      - name: Build AAB APK
        script: |
          flutter build appbundle --release
          flutter build apk --release

      - name: Publish to GitHub
        script: |
          #!/usr/bin/env zsh
          
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
                
          RELEASE_NAME="release-${COMMIT_HASH}"
          
          # Periksa file APK dan AAB
          APK_PATH="build/app/outputs/apk/release/app-release.apk"
          AAB_PATH="build/app/outputs/bundle/release/app-release.aab"
          
          if [[ ! -f "${APK_PATH}" ]] && [[ ! -f "${AAB_PATH}" ]]; then
            echo "Error: No APK or AAB files found in the specified paths."
            exit 1
          fi
          
          FILES=""
          [[ -f "${APK_PATH}" ]] && FILES="${FILES} ${APK_PATH}"
          [[ -f "${AAB_PATH}" ]] && FILES="${FILES} ${AAB_PATH}"
          
          gh release create "${RELEASE_NAME}" \
            --title "Ditonton release from ${BRANCH_NAME} (${COMMIT_HASH})" \
            ${FILES} || { echo "Failed to create release"; exit 1; }
            
          echo "Release successfully created: ${RELEASE_NAME}"

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
      - coverage/*.info

    publishing:
      email:
        recipients:
          - kdkfrdy@gmail.com
        notify:
          success: true
          failure: true

      scripts:
        - name: Check for apk
          script: |
            apkPath=$(find build -name "*.apk" | head -1)
            if [[ -z ${apkPath} ]]
            then
              echo "No .apk were found"
            else
              echo "Publishing .apk artifacts"
            fi

        - name: Check for aab
          script: |
            aabPath=$(find build -name "*.aab" | head -1)
            if [[ -z ${aabPath} ]]
            then
              echo "No .aab were found"
            else
              echo "Publishing .aab artifacts"
            fi