workflows:
  default-workflow:
    name: Default Workflow for ditonton
    instance_type: mac_mini_m2
    max_build_duration: 60

    inputs:
      name:
        description: Input description
        default: Codemagic

    environment:
      groups:
        - firebase_credentials
      flutter: stable
      xcode: latest
      android_signing:
        - keystore_ditonton

    cache:
      cache_paths:
        - ~/.pub-cache

    triggering:
      events:
        - push

      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Flutter build and test
        script: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter test
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e # exit on first failed command

          PROJECT_ROOT=$CM_BUILD_DIR   # ADD YOUR PROJECT FOLDER PATH HERE

          echo "Decoding Firebase credentials..."
          echo $ANDROID_FIREBASE_SECRET | base64 --decode > $PROJECT_ROOT/android/app/google-services.json
          echo $IOS_FIREBASE_SECRET | base64 --decode > $PROJECT_ROOT/ios/Runner/GoogleService-Info.plist
          echo "Firebase configuration successfully loaded!"
      - name: Build Universal APK
        script: |
          android-app-bundle build-universal-apk \
            --bundle 'project_directory/build/**/outputs/**/*.aab' \
            --ks /tmp/keystore.keystore \
            --ks-pass $CM_KEYSTORE_PASSWORD \
            --ks-key-alias $CM_KEY_ALIAS \
            --key-pass $CM_KEY_PASSWORD

    artifacts:
      - build/**/outputs/**/**/*.apk
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - kdkfrdy@gmail.com
        notify:
          success: true
          failure: true

      scripts:
        - name: Check for apk
          script: |
            apkPath=$(find build -name "*.apk" | head -1)
            if [[ -z ${apkPath} ]]
            then
              echo "No .apk were found"
            else
              echo "Publishing .apk artifacts"
            fi