environment:
  groups:
    - firebase_credentials


scripts:
  - name: Load Firebase configuration
    script: |
      #!/usr/bin/env sh
      set -e # exit on first failed command

      PROJECT_ROOT=$CM_BUILD_DIR/ditonton    # ADD YOUR PROJECT FOLDER PATH HERE

      echo "Decoding Firebase credentials..."
      echo $ANDROID_FIREBASE_SECRET | base64 --decode > $PROJECT_ROOT/android/app/google-services.json
      echo $IOS_FIREBASE_SECRET | base64 --decode > $PROJECT_ROOT/ios/Runner/GoogleService-Info.plist
      echo "Firebase configuration successfully loaded!"