// Mocks generated by Mockito 5.4.5 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i24;
import 'dart:typed_data' as _i25;

import 'package:core/common/failure.dart' as _i10;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/io_client.dart' as _i6;
import 'package:http/src/base_request.dart' as _i23;
import 'package:http/src/response.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:sqflite/sqflite.dart' as _i21;
import 'package:tv/data/datasources/db/database_helper.dart' as _i20;
import 'package:tv/data/datasources/network/network_helper.dart' as _i22;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i17;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i15;
import 'package:tv/data/models/tv/tv_detail/episode_response.dart' as _i5;
import 'package:tv/data/models/tv/tv_detail/season_response.dart' as _i4;
import 'package:tv/data/models/tv/tv_detail/tv_detail_model.dart' as _i3;
import 'package:tv/data/models/tv/tv_model.dart' as _i16;
import 'package:tv/data/models/tv/tv_table.dart' as _i18;
import 'package:tv/domain/entities/tv/episode/episode.dart' as _i14;
import 'package:tv/domain/entities/tv/season/season_detail.dart' as _i13;
import 'package:tv/domain/entities/tv/tv.dart' as _i11;
import 'package:tv/domain/entities/tv/tv_detail.dart' as _i12;
import 'package:tv/domain/repositories/tv_repository.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSeasonResponse_2 extends _i1.SmartFake
    implements _i4.SeasonResponse {
  _FakeSeasonResponse_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeEpisodeResponse_3 extends _i1.SmartFake
    implements _i5.EpisodeResponse {
  _FakeEpisodeResponse_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIOClient_4 extends _i1.SmartFake implements _i6.IOClient {
  _FakeIOClient_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIOStreamedResponse_5 extends _i1.SmartFake
    implements _i6.IOStreamedResponse {
  _FakeIOStreamedResponse_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_6 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i8.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>
      getNowPlayingTvSeries() => (super.noSuchMethod(
            Invocation.method(#getNowPlayingTvSeries, []),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>.value(
              _FakeEither_0<_i10.Failure, List<_i11.TvSeries>>(
                this,
                Invocation.method(#getNowPlayingTvSeries, []),
              ),
            ),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>.value(
              _FakeEither_0<_i10.Failure, List<_i11.TvSeries>>(
                this,
                Invocation.method(#getPopularTvSeries, []),
              ),
            ),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>.value(
              _FakeEither_0<_i10.Failure, List<_i11.TvSeries>>(
                this,
                Invocation.method(#getTopRatedTvSeries, []),
              ),
            ),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i12.TvSeriesDetail>> getTvSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getTvSeriesDetail, [id]),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i12.TvSeriesDetail>>.value(
          _FakeEither_0<_i10.Failure, _i12.TvSeriesDetail>(
            this,
            Invocation.method(#getTvSeriesDetail, [id]),
          ),
        ),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i12.TvSeriesDetail>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i13.Season>> getTvSeriesSeasonDetail({
    required int? id,
    required int? seasonNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTvSeriesSeasonDetail, [], {
          #id: id,
          #seasonNumber: seasonNumber,
        }),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, _i13.Season>>.value(
          _FakeEither_0<_i10.Failure, _i13.Season>(
            this,
            Invocation.method(#getTvSeriesSeasonDetail, [], {
              #id: id,
              #seasonNumber: seasonNumber,
            }),
          ),
        ),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i13.Season>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i14.Episode>>
      getTvSeriesSeasonEpisodeDetail({
    required int? id,
    required int? seasonNumber,
    required int? episodeNumber,
  }) =>
          (super.noSuchMethod(
            Invocation.method(#getTvSeriesSeasonEpisodeDetail, [], {
              #id: id,
              #seasonNumber: seasonNumber,
              #episodeNumber: episodeNumber,
            }),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, _i14.Episode>>.value(
              _FakeEither_0<_i10.Failure, _i14.Episode>(
                this,
                Invocation.method(#getTvSeriesSeasonEpisodeDetail, [], {
                  #id: id,
                  #seasonNumber: seasonNumber,
                  #episodeNumber: episodeNumber,
                }),
              ),
            ),
          ) as _i9.Future<_i2.Either<_i10.Failure, _i14.Episode>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>
      getTvSeriesRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>.value(
              _FakeEither_0<_i10.Failure, List<_i11.TvSeries>>(
                this,
                Invocation.method(#getTvSeriesRecommendations, [id]),
              ),
            ),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#searchTvSeries, [query]),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>.value(
          _FakeEither_0<_i10.Failure, List<_i11.TvSeries>>(
            this,
            Invocation.method(#searchTvSeries, [query]),
          ),
        ),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> saveWatchlist(
    _i12.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#saveWatchlist, [tvSeries]),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
          _FakeEither_0<_i10.Failure, String>(
            this,
            Invocation.method(#saveWatchlist, [tvSeries]),
          ),
        ),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> removeWatchlist(
    _i12.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [tvSeries]),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
          _FakeEither_0<_i10.Failure, String>(
            this,
            Invocation.method(#removeWatchlist, [tvSeries]),
          ),
        ),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(#isAddedToWatchlist, [id]),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>
      getWatchlistTvSeries() => (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>.value(
              _FakeEither_0<_i10.Failure, List<_i11.TvSeries>>(
                this,
                Invocation.method(#getWatchlistTvSeries, []),
              ),
            ),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.TvSeries>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i15.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i16.TvSeriesModel>> getNowPlayingTv() => (super.noSuchMethod(
        Invocation.method(#getNowPlayingTv, []),
        returnValue: _i9.Future<List<_i16.TvSeriesModel>>.value(
          <_i16.TvSeriesModel>[],
        ),
      ) as _i9.Future<List<_i16.TvSeriesModel>>);

  @override
  _i9.Future<List<_i16.TvSeriesModel>> getPopularTv() => (super.noSuchMethod(
        Invocation.method(#getPopularTv, []),
        returnValue: _i9.Future<List<_i16.TvSeriesModel>>.value(
          <_i16.TvSeriesModel>[],
        ),
      ) as _i9.Future<List<_i16.TvSeriesModel>>);

  @override
  _i9.Future<List<_i16.TvSeriesModel>> getTopRatedTv() => (super.noSuchMethod(
        Invocation.method(#getTopRatedTv, []),
        returnValue: _i9.Future<List<_i16.TvSeriesModel>>.value(
          <_i16.TvSeriesModel>[],
        ),
      ) as _i9.Future<List<_i16.TvSeriesModel>>);

  @override
  _i9.Future<_i3.TvSeriesDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getTvDetail, [id]),
        returnValue: _i9.Future<_i3.TvSeriesDetailResponse>.value(
          _FakeTvSeriesDetailResponse_1(
            this,
            Invocation.method(#getTvDetail, [id]),
          ),
        ),
      ) as _i9.Future<_i3.TvSeriesDetailResponse>);

  @override
  _i9.Future<List<_i16.TvSeriesModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getTvRecommendations, [id]),
        returnValue: _i9.Future<List<_i16.TvSeriesModel>>.value(
          <_i16.TvSeriesModel>[],
        ),
      ) as _i9.Future<List<_i16.TvSeriesModel>>);

  @override
  _i9.Future<List<_i16.TvSeriesModel>> searchTv(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchTv, [query]),
        returnValue: _i9.Future<List<_i16.TvSeriesModel>>.value(
          <_i16.TvSeriesModel>[],
        ),
      ) as _i9.Future<List<_i16.TvSeriesModel>>);

  @override
  _i9.Future<_i4.SeasonResponse> getTvDetailSeason({
    required int? id,
    required int? seasonNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTvDetailSeason, [], {
          #id: id,
          #seasonNumber: seasonNumber,
        }),
        returnValue: _i9.Future<_i4.SeasonResponse>.value(
          _FakeSeasonResponse_2(
            this,
            Invocation.method(#getTvDetailSeason, [], {
              #id: id,
              #seasonNumber: seasonNumber,
            }),
          ),
        ),
      ) as _i9.Future<_i4.SeasonResponse>);

  @override
  _i9.Future<_i5.EpisodeResponse> getTvDetailSeasonEpisode({
    required int? id,
    required int? seasonNumber,
    required int? episodeNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTvDetailSeasonEpisode, [], {
          #id: id,
          #seasonNumber: seasonNumber,
          #episodeNumber: episodeNumber,
        }),
        returnValue: _i9.Future<_i5.EpisodeResponse>.value(
          _FakeEpisodeResponse_3(
            this,
            Invocation.method(#getTvDetailSeasonEpisode, [], {
              #id: id,
              #seasonNumber: seasonNumber,
              #episodeNumber: episodeNumber,
            }),
          ),
        ),
      ) as _i9.Future<_i5.EpisodeResponse>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i17.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchlist(_i18.TvTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#insertWatchlist, [movie]),
        returnValue: _i9.Future<String>.value(
          _i19.dummyValue<String>(
            this,
            Invocation.method(#insertWatchlist, [movie]),
          ),
        ),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> removeWatchlist(_i18.TvTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [movie]),
        returnValue: _i9.Future<String>.value(
          _i19.dummyValue<String>(
            this,
            Invocation.method(#removeWatchlist, [movie]),
          ),
        ),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i18.TvTable?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(#getTvById, [id]),
        returnValue: _i9.Future<_i18.TvTable?>.value(),
      ) as _i9.Future<_i18.TvTable?>);

  @override
  _i9.Future<List<_i18.TvTable>> getWatchlistTv() => (super.noSuchMethod(
        Invocation.method(#getWatchlistTv, []),
        returnValue: _i9.Future<List<_i18.TvTable>>.value(<_i18.TvTable>[]),
      ) as _i9.Future<List<_i18.TvTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i20.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i21.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i9.Future<_i21.Database?>.value(),
      ) as _i9.Future<_i21.Database?>);

  @override
  _i9.Future<int> insertWatchlistTv(_i18.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(#insertWatchlistTv, [tv]),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> removeWatchlistTv(_i18.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(#removeWatchlistTv, [tv]),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<Map<String, dynamic>?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(#getTvById, [id]),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistTv, []),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
      ) as _i9.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [NetworkHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHelper extends _i1.Mock implements _i22.NetworkHelper {
  MockNetworkHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.IOClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeIOClient_4(this, Invocation.getter(#client)),
      ) as _i6.IOClient);
}

/// A class which mocks [IOClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOClient extends _i1.Mock implements _i6.IOClient {
  MockIOClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.IOStreamedResponse> send(_i23.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(#send, [request]),
        returnValue: _i9.Future<_i6.IOStreamedResponse>.value(
          _FakeIOStreamedResponse_5(
            this,
            Invocation.method(#send, [request]),
          ),
        ),
      ) as _i9.Future<_i6.IOStreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(#close, []),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#head, [url], {#headers: headers}),
        returnValue: _i9.Future<_i7.Response>.value(
          _FakeResponse_6(
            this,
            Invocation.method(#head, [url], {#headers: headers}),
          ),
        ),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#get, [url], {#headers: headers}),
        returnValue: _i9.Future<_i7.Response>.value(
          _FakeResponse_6(
            this,
            Invocation.method(#get, [url], {#headers: headers}),
          ),
        ),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i24.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i9.Future<_i7.Response>.value(
          _FakeResponse_6(
            this,
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i24.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i9.Future<_i7.Response>.value(
          _FakeResponse_6(
            this,
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i24.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i9.Future<_i7.Response>.value(
          _FakeResponse_6(
            this,
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i24.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i9.Future<_i7.Response>.value(
          _FakeResponse_6(
            this,
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#read, [url], {#headers: headers}),
        returnValue: _i9.Future<String>.value(
          _i19.dummyValue<String>(
            this,
            Invocation.method(#read, [url], {#headers: headers}),
          ),
        ),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i25.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#readBytes, [url], {#headers: headers}),
        returnValue: _i9.Future<_i25.Uint8List>.value(_i25.Uint8List(0)),
      ) as _i9.Future<_i25.Uint8List>);
}
