// Mocks generated by Mockito 5.4.5 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i32;
import 'dart:typed_data' as _i33;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i11;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i28;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i16;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i14;
import 'package:ditonton/data/datasources/network/network_helper.dart' as _i30;
import 'package:ditonton/data/datasources/tv_local_data_source.dart' as _i26;
import 'package:ditonton/data/datasources/tv_remote_data_source.dart' as _i24;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i15;
import 'package:ditonton/data/models/movie_table.dart' as _i17;
import 'package:ditonton/data/models/tv/tv_detail/episode_response.dart' as _i6;
import 'package:ditonton/data/models/tv/tv_detail/season_response.dart' as _i5;
import 'package:ditonton/data/models/tv/tv_detail/tv_detail_model.dart' as _i4;
import 'package:ditonton/data/models/tv/tv_model.dart' as _i25;
import 'package:ditonton/data/models/tv/tv_table.dart' as _i27;
import 'package:ditonton/domain/entities/movie.dart' as _i12;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i13;
import 'package:ditonton/domain/entities/tv/episode/episode.dart' as _i23;
import 'package:ditonton/domain/entities/tv/season/season_detail.dart' as _i22;
import 'package:ditonton/domain/entities/tv/tv.dart' as _i20;
import 'package:ditonton/domain/entities/tv/tv_detail.dart' as _i21;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i9;
import 'package:ditonton/domain/repositories/tv_repository.dart' as _i19;
import 'package:http/io_client.dart' as _i7;
import 'package:http/src/base_request.dart' as _i31;
import 'package:http/src/response.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:sqflite/sqflite.dart' as _i29;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailResponse_2 extends _i1.SmartFake
    implements _i4.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSeasonResponse_3 extends _i1.SmartFake
    implements _i5.SeasonResponse {
  _FakeSeasonResponse_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeEpisodeResponse_4 extends _i1.SmartFake
    implements _i6.EpisodeResponse {
  _FakeEpisodeResponse_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIOClient_5 extends _i1.SmartFake implements _i7.IOClient {
  _FakeIOClient_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIOStreamedResponse_6 extends _i1.SmartFake
    implements _i7.IOStreamedResponse {
  _FakeIOStreamedResponse_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_7 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i9.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getNowPlayingMovies() => (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
                this,
                Invocation.method(#getNowPlayingMovies, []),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getPopularMovies, []),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
          _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
            this,
            Invocation.method(#getPopularMovies, []),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getTopRatedMovies, []),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
          _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
            this,
            Invocation.method(#getTopRatedMovies, []),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i13.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getMovieDetail, [id]),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i13.MovieDetail>>.value(
          _FakeEither_0<_i11.Failure, _i13.MovieDetail>(
            this,
            Invocation.method(#getMovieDetail, [id]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i13.MovieDetail>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
                this,
                Invocation.method(#getMovieRecommendations, [id]),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#searchMovies, [query]),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
          _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
            this,
            Invocation.method(#searchMovies, [query]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> saveWatchlist(
    _i13.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#saveWatchlist, [movie]),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
          _FakeEither_0<_i11.Failure, String>(
            this,
            Invocation.method(#saveWatchlist, [movie]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> removeWatchlist(
    _i13.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [movie]),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
          _FakeEither_0<_i11.Failure, String>(
            this,
            Invocation.method(#removeWatchlist, [movie]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);

  @override
  _i10.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(#isAddedToWatchlist, [id]),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getWatchlistMovies() => (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
                this,
                Invocation.method(#getWatchlistMovies, []),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i14.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i15.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getNowPlayingMovies, []),
        returnValue: _i10.Future<List<_i15.MovieModel>>.value(
          <_i15.MovieModel>[],
        ),
      ) as _i10.Future<List<_i15.MovieModel>>);

  @override
  _i10.Future<List<_i15.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(#getPopularMovies, []),
        returnValue: _i10.Future<List<_i15.MovieModel>>.value(
          <_i15.MovieModel>[],
        ),
      ) as _i10.Future<List<_i15.MovieModel>>);

  @override
  _i10.Future<List<_i15.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(#getTopRatedMovies, []),
        returnValue: _i10.Future<List<_i15.MovieModel>>.value(
          <_i15.MovieModel>[],
        ),
      ) as _i10.Future<List<_i15.MovieModel>>);

  @override
  _i10.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getMovieDetail, [id]),
        returnValue: _i10.Future<_i3.MovieDetailResponse>.value(
          _FakeMovieDetailResponse_1(
            this,
            Invocation.method(#getMovieDetail, [id]),
          ),
        ),
      ) as _i10.Future<_i3.MovieDetailResponse>);

  @override
  _i10.Future<List<_i15.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getMovieRecommendations, [id]),
        returnValue: _i10.Future<List<_i15.MovieModel>>.value(
          <_i15.MovieModel>[],
        ),
      ) as _i10.Future<List<_i15.MovieModel>>);

  @override
  _i10.Future<List<_i15.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchMovies, [query]),
        returnValue: _i10.Future<List<_i15.MovieModel>>.value(
          <_i15.MovieModel>[],
        ),
      ) as _i10.Future<List<_i15.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i16.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> insertWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#insertWatchlist, [movie]),
        returnValue: _i10.Future<String>.value(
          _i18.dummyValue<String>(
            this,
            Invocation.method(#insertWatchlist, [movie]),
          ),
        ),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> removeWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [movie]),
        returnValue: _i10.Future<String>.value(
          _i18.dummyValue<String>(
            this,
            Invocation.method(#removeWatchlist, [movie]),
          ),
        ),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i17.MovieTable?> getMovieById(int? id) => (super.noSuchMethod(
        Invocation.method(#getMovieById, [id]),
        returnValue: _i10.Future<_i17.MovieTable?>.value(),
      ) as _i10.Future<_i17.MovieTable?>);

  @override
  _i10.Future<List<_i17.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistMovies, []),
        returnValue: _i10.Future<List<_i17.MovieTable>>.value(
          <_i17.MovieTable>[],
        ),
      ) as _i10.Future<List<_i17.MovieTable>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i19.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>
      getNowPlayingTvSeries() => (super.noSuchMethod(
            Invocation.method(#getNowPlayingTvSeries, []),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>.value(
              _FakeEither_0<_i11.Failure, List<_i20.TvSeries>>(
                this,
                Invocation.method(#getNowPlayingTvSeries, []),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>.value(
              _FakeEither_0<_i11.Failure, List<_i20.TvSeries>>(
                this,
                Invocation.method(#getPopularTvSeries, []),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>.value(
              _FakeEither_0<_i11.Failure, List<_i20.TvSeries>>(
                this,
                Invocation.method(#getTopRatedTvSeries, []),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i21.TvSeriesDetail>> getTvSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getTvSeriesDetail, [id]),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i21.TvSeriesDetail>>.value(
          _FakeEither_0<_i11.Failure, _i21.TvSeriesDetail>(
            this,
            Invocation.method(#getTvSeriesDetail, [id]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i21.TvSeriesDetail>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i22.Season>> getTvSeriesSeasonDetail({
    required int? id,
    required int? seasonNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTvSeriesSeasonDetail, [], {
          #id: id,
          #seasonNumber: seasonNumber,
        }),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, _i22.Season>>.value(
          _FakeEither_0<_i11.Failure, _i22.Season>(
            this,
            Invocation.method(#getTvSeriesSeasonDetail, [], {
              #id: id,
              #seasonNumber: seasonNumber,
            }),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i22.Season>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i23.Episode>>
      getTvSeriesSeasonEpisodeDetail({
    required int? id,
    required int? seasonNumber,
    required int? episodeNumber,
  }) =>
          (super.noSuchMethod(
            Invocation.method(#getTvSeriesSeasonEpisodeDetail, [], {
              #id: id,
              #seasonNumber: seasonNumber,
              #episodeNumber: episodeNumber,
            }),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, _i23.Episode>>.value(
              _FakeEither_0<_i11.Failure, _i23.Episode>(
                this,
                Invocation.method(#getTvSeriesSeasonEpisodeDetail, [], {
                  #id: id,
                  #seasonNumber: seasonNumber,
                  #episodeNumber: episodeNumber,
                }),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, _i23.Episode>>);

  @override
  _i10.Future<
      _i2.Either<_i11.Failure, List<_i20.TvSeries>>> getTvSeriesRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getTvSeriesRecommendations, [id]),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>.value(
          _FakeEither_0<_i11.Failure, List<_i20.TvSeries>>(
            this,
            Invocation.method(#getTvSeriesRecommendations, [id]),
          ),
            ),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#searchTvSeries, [query]),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>.value(
          _FakeEither_0<_i11.Failure, List<_i20.TvSeries>>(
            this,
            Invocation.method(#searchTvSeries, [query]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> saveWatchlist(
    _i21.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#saveWatchlist, [tvSeries]),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
          _FakeEither_0<_i11.Failure, String>(
            this,
            Invocation.method(#saveWatchlist, [tvSeries]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> removeWatchlist(
    _i21.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [tvSeries]),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
          _FakeEither_0<_i11.Failure, String>(
            this,
            Invocation.method(#removeWatchlist, [tvSeries]),
          ),
        ),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);

  @override
  _i10.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(#isAddedToWatchlist, [id]),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>
      getWatchlistTvSeries() => (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>.value(
              _FakeEither_0<_i11.Failure, List<_i20.TvSeries>>(
                this,
                Invocation.method(#getWatchlistTvSeries, []),
              ),
            ),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.TvSeries>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i24.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i25.TvSeriesModel>> getNowPlayingTv() =>
      (super.noSuchMethod(
        Invocation.method(#getNowPlayingTv, []),
        returnValue: _i10.Future<List<_i25.TvSeriesModel>>.value(
          <_i25.TvSeriesModel>[],
        ),
      ) as _i10.Future<List<_i25.TvSeriesModel>>);

  @override
  _i10.Future<List<_i25.TvSeriesModel>> getPopularTv() => (super.noSuchMethod(
        Invocation.method(#getPopularTv, []),
        returnValue: _i10.Future<List<_i25.TvSeriesModel>>.value(
          <_i25.TvSeriesModel>[],
        ),
      ) as _i10.Future<List<_i25.TvSeriesModel>>);

  @override
  _i10.Future<List<_i25.TvSeriesModel>> getTopRatedTv() => (super.noSuchMethod(
        Invocation.method(#getTopRatedTv, []),
        returnValue: _i10.Future<List<_i25.TvSeriesModel>>.value(
          <_i25.TvSeriesModel>[],
        ),
      ) as _i10.Future<List<_i25.TvSeriesModel>>);

  @override
  _i10.Future<_i4.TvSeriesDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getTvDetail, [id]),
        returnValue: _i10.Future<_i4.TvSeriesDetailResponse>.value(
          _FakeTvSeriesDetailResponse_2(
            this,
            Invocation.method(#getTvDetail, [id]),
          ),
        ),
      ) as _i10.Future<_i4.TvSeriesDetailResponse>);

  @override
  _i10.Future<List<_i25.TvSeriesModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getTvRecommendations, [id]),
        returnValue: _i10.Future<List<_i25.TvSeriesModel>>.value(
          <_i25.TvSeriesModel>[],
        ),
      ) as _i10.Future<List<_i25.TvSeriesModel>>);

  @override
  _i10.Future<List<_i25.TvSeriesModel>> searchTv(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchTv, [query]),
        returnValue: _i10.Future<List<_i25.TvSeriesModel>>.value(
          <_i25.TvSeriesModel>[],
        ),
      ) as _i10.Future<List<_i25.TvSeriesModel>>);

  @override
  _i10.Future<_i5.SeasonResponse> getTvDetailSeason({
    required int? id,
    required int? seasonNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTvDetailSeason, [], {
          #id: id,
          #seasonNumber: seasonNumber,
        }),
        returnValue: _i10.Future<_i5.SeasonResponse>.value(
          _FakeSeasonResponse_3(
            this,
            Invocation.method(#getTvDetailSeason, [], {
              #id: id,
              #seasonNumber: seasonNumber,
            }),
          ),
        ),
      ) as _i10.Future<_i5.SeasonResponse>);

  @override
  _i10.Future<_i6.EpisodeResponse> getTvDetailSeasonEpisode({
    required int? id,
    required int? seasonNumber,
    required int? episodeNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTvDetailSeasonEpisode, [], {
          #id: id,
          #seasonNumber: seasonNumber,
          #episodeNumber: episodeNumber,
        }),
        returnValue: _i10.Future<_i6.EpisodeResponse>.value(
          _FakeEpisodeResponse_4(
            this,
            Invocation.method(#getTvDetailSeasonEpisode, [], {
              #id: id,
              #seasonNumber: seasonNumber,
              #episodeNumber: episodeNumber,
            }),
          ),
        ),
      ) as _i10.Future<_i6.EpisodeResponse>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i26.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> insertWatchlist(_i27.TvTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#insertWatchlist, [movie]),
        returnValue: _i10.Future<String>.value(
          _i18.dummyValue<String>(
            this,
            Invocation.method(#insertWatchlist, [movie]),
          ),
        ),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> removeWatchlist(_i27.TvTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [movie]),
        returnValue: _i10.Future<String>.value(
          _i18.dummyValue<String>(
            this,
            Invocation.method(#removeWatchlist, [movie]),
          ),
        ),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i27.TvTable?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(#getTvById, [id]),
        returnValue: _i10.Future<_i27.TvTable?>.value(),
      ) as _i10.Future<_i27.TvTable?>);

  @override
  _i10.Future<List<_i27.TvTable>> getWatchlistTv() => (super.noSuchMethod(
        Invocation.method(#getWatchlistTv, []),
        returnValue: _i10.Future<List<_i27.TvTable>>.value(
          <_i27.TvTable>[],
        ),
      ) as _i10.Future<List<_i27.TvTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i28.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i29.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i10.Future<_i29.Database?>.value(),
      ) as _i10.Future<_i29.Database?>);

  @override
  _i10.Future<int> insertWatchlistMovie(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#insertWatchlistMovie, [movie]),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> removeWatchlistMovie(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlistMovie, [movie]),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getMovieById, [id]),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistMovies, []),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
      ) as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<int> insertWatchlistTv(_i27.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(#insertWatchlistTv, [tv]),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> removeWatchlistTv(_i27.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(#removeWatchlistTv, [tv]),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<Map<String, dynamic>?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(#getTvById, [id]),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistTv, []),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
      ) as _i10.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [NetworkHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHelper extends _i1.Mock implements _i30.NetworkHelper {
  MockNetworkHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.IOClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeIOClient_5(this, Invocation.getter(#client)),
      ) as _i7.IOClient);
}

/// A class which mocks [IOClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOClient extends _i1.Mock implements _i7.IOClient {
  MockIOClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i7.IOStreamedResponse> send(_i31.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(#send, [request]),
        returnValue: _i10.Future<_i7.IOStreamedResponse>.value(
          _FakeIOStreamedResponse_6(
            this,
            Invocation.method(#send, [request]),
          ),
        ),
      ) as _i10.Future<_i7.IOStreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(#close, []),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i8.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#head, [url], {#headers: headers}),
        returnValue: _i10.Future<_i8.Response>.value(
          _FakeResponse_7(
            this,
            Invocation.method(#head, [url], {#headers: headers}),
          ),
        ),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#get, [url], {#headers: headers}),
        returnValue: _i10.Future<_i8.Response>.value(
          _FakeResponse_7(
            this,
            Invocation.method(#get, [url], {#headers: headers}),
          ),
        ),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i32.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i10.Future<_i8.Response>.value(
          _FakeResponse_7(
            this,
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i32.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i10.Future<_i8.Response>.value(
          _FakeResponse_7(
            this,
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i32.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i10.Future<_i8.Response>.value(
          _FakeResponse_7(
            this,
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i32.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i10.Future<_i8.Response>.value(
          _FakeResponse_7(
            this,
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
          ),
        ),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#read, [url], {#headers: headers}),
        returnValue: _i10.Future<String>.value(
          _i18.dummyValue<String>(
            this,
            Invocation.method(#read, [url], {#headers: headers}),
          ),
        ),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i33.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#readBytes, [url], {#headers: headers}),
        returnValue: _i10.Future<_i33.Uint8List>.value(_i33.Uint8List(0)),
      ) as _i10.Future<_i33.Uint8List>);
}
